ARG BASE_IMAGE=docker.io/library/python:3.11-bookworm
FROM ${BASE_IMAGE}

WORKDIR /app

COPY run_linktransformer ./run_linktransformer

ENTRYPOINT ["python3", "run_linktransformer/run_embeddings_partitioned.py"]
